(function(window){
	var lang = function(str) {
		var localize = navigator.language || navigator.userLanguage;
        var def = 'en';
		if(typeof localize == 'undefined') {
			localize = def;
		}
		else {
			var local = localize.split('-');
			localize = local[0];
		}
		var store = {
			'es': {
				'title': 'GameBater - Intenta no correrte',
				'p1-step1-1': '¡Cierra la puerta antes de comenzar este juego!',
                'p1-step1-2': 'No lo comentes!',
				'p1-step1-3': 'Juega',
                'p1-step2-1': 'Créala, Disfrútala',
                'p1-step2-2': 'Dejarla embarazada',
                'p1-step2-3': 'No, gracias',
                'p1-step2-4': 'Continuar',
                'p1-step3-1': 'Elige tu primera',
                'p1-step3-2': 'pareja sexual',
                'p1-step3-3': '&#171; Lisa',
                'p1-step3-4': 'Elsa &#187;',
                'p1-step4-1': 'Advertencia',
                'p1-step4-2': '¡Trata de controlarte!',
                'p1-step4-3': 'Juega',
                'p2-step1-1': 'Juegos para adultos',
                'p2-step1-2': 'Te No durarás ni 40 segundos',
				'p2-step1-3': 'Comienza el juego',
                'p2-step1-4': 'Al hacer clic en COMIENZA EL JUEGO confirmas que eres mayor de 18 años',
                'p2-step2-1': 'Antes de permitirte probar nuestros juegos para adultos, necesitamos hacerte algunas breves preguntas.',
                'p2-step2-2': 'Esta información personalizará tu experiencia en el juego para que te experimentar más sensaciones.',
				'p2-step2-3': 'Continuar',
                'p2-step3-1': 'Nuestros juegos son muy adictivos y verás muchas escenas sexuales. ¿Podrás soportarlo?',
                'p2-step3-2': 'Sí',
				'p2-step3-3': 'No',
                'p2-step4-1': '¿A quién te gustaría llevar a la cama en estos juegos?',
                'p2-step4-2': 'Tu madre u otro familiar',
                'p2-step4-3': 'Vecina',
                'p2-step4-4': 'Dibujos animados famosos',
                'p2-step4-5': 'Otros',
                'p2-step5-1': '¿De qué tamaño quieres que sean sus tetas?',
                'p2-step5-2': 'Pequeñas',
                'p2-step5-3': 'Medianas',
                'p2-step5-4': 'Grandes',
                'p2-step5-5': 'Inmensas',
                'p2-step6-1': '¿Cómo te gusta su coño?',
                'p2-step6-2': 'Afeitado',
                'p2-step6-3': 'Acicalado',
                'p2-step6-4': 'Con vello',
                'p2-step7-1': '¡Bien! Tenemos más de 1.800 juegos para ti. Puedes jugar solo y con varios jugadores.',
                'p2-step7-2': 'Pero antes de empezar, ¿qué tipo de juego te gustaría?',
                'p2-step7-3': 'Juego para correrse rápidamente',
                'p2-step7-4': 'Juego de rol',
                'p2-step8-1': '¿Quieres un juego de sexo duro?',
                'p2-step8-2': 'Sí',
                'p2-step8-3': 'No',
                'p2-step9-1': '¿Has cerrado la puerta de la habitación y ya estás listo para сontinuar?',
                'p2-step9-2': 'Sí',
                'p2-step9-3': 'No',
                'p2-step10-1': '¿En cuánto tiempo quieres terminarlo?',
                'p2-step10-2': 'En 20 segundos',
                'p2-step10-3': 'En 5 minutos',
                'p2-step11-1': '¿Cuántas veces quieres terminarlo?',
                'p2-step11-2': 'Dos veces',
                'p2-step11-3': 'Solo una vez',
                'p2-step12-1': 'Elige la dificultad del juego',
                'p2-step12-2': 'Fácil',
                'p2-step12-3': 'Regular',
                'p2-step12-4': 'Difícil',
                'p2-step12-5': 'Extrema',
                'p2-step13-1': 'Para poder crear tu personaje, debes elegir tu nombre de usuario y contraseña ¿Entiendes y aceptas nuestros términos?',
                'p2-step13-2': 'Sí',
                'p2-step13-3': 'No',
                'p2-step14-1': 'Analizando',
                'p2-step15-1': 'Felicidades',
                'p2-step15-2': 'Hemos encontrado 11.131 jugadores en línea con tus preferencias',
                'p2-step15-3': 'Continuar',
                'p2-step16-1': 'Por favor, recuerda:',
                'p2-step16-2': '1. Nuestros juegos son extremandamente adictivos',
                'p2-step16-3': '2. Te recomendamos que juegues a solas',
                'p2-step16-4': '3. Cierra la puerta antes de jugar',
                'p2-step16-5': 'Estoy de acuerdo',
                'p2-step17-1': 'Nuestro simulador es compatible con',
                'p2-step17-2': 'No es necesaria ninguna descarga',
                'p2-step17-3': 'Continuar',
                'p2-step18-1': 'Buscando sala de juegos',
                'p2-step18-2': '¡Juego encontrado!',
                'p2-step18-3': 'Revisando las respuestas',
                'p2-step18-4': 'Detección de la compatibilidad del navegador¡',
                'p2-step18-5': 'es compatible con el juego!',
                'p2-step18-6': 'Continuar',
                'faq1':'Tienes preguntas?',
                'faq2':'Consulte nuestras preguntas frecuentes',
                'faq':'Preguntas frecuentes',
                'faq-1':'¿Qué es GameBater?',
                'faq-2':'¡GameBater es la comunidad más grande de juegos en línea para adultos! Todos los días se juegan miles de juegos sexuales en línea y sin conexión.',
                'faq-3':'¿Tengo que pagar por ello?',
                'faq-4':'¡Nuestros juegos son absolutamente GRATUITOS! ¡Lo único que necesitas es un correo electrónico válido y estarás listo para comenzar!',
                'faq-5':'Si es gratuito, ¿por qué necesito una tarjeta de crédito?',
                'faq-6':'La autenticación de la tarjeta de crédito es nuestro método para verificar la edad. GameBater solo es accesible para quienes alcancen la mayoría de edad legal, 18 años o más.',
                'faq-7':'¿Necesito conexión a internet para jugar?',
                'faq-8':'No. Una vez te registres, podrás jugar en línea o sin conexión. ',
                'faq-9':'¿Puedo jugar a estos juegos en varios dispositivos?',
                'faq-10':'Sí. Puedes jugar con cualquier cantidad de dispositivos.',
                'faq-11':'¿Es seguro?',
                'faq-12':'Valoramos tu privacidad y tu seguridad, y nunca compartiremos tu información. Tu actividad en GameBater es 100 % privada y discreta.',
                'faq-13':'¿Necesito instalar alguna aplicación o software?',
                'faq-14':'¡Por supuesto que no! GameBater está basado en la web en un 100%, y no requiere ninguna instalación de software o complementos. ¡Tan solo regístrate GRATUITAMENTE y estarás listo para comenzar! ',
                'faq-15':'¿Por qué me reenvían a una página diferente tras contestar a las preguntas?',
                'faq-16':'GameBater colabora con varios servicios para proporcionarte la mejor experiencia de juego posible, pero no dudes que tu información se trasmite de forma segura.'
			},
			'en': {
				'title': 'GameBater - Try Not To Cum',
				'p1-step1-1': 'Lock Your Door Before You Play This Game!',
                'p1-step1-2': 'Don\'t spread the word!',
				'p1-step1-3': 'Play Game',
                'p1-step2-1': 'Build Her, Enjoy Her',
                'p1-step2-2': 'Impregnate',
                'p1-step2-3': 'No, Thanks',
                'p1-step2-4': 'Continue',
                'p1-step3-1': 'Choose Your First',
                'p1-step3-2': 'Sexual Partner',
                'p1-step3-3': '&#171; Lisa',
                'p1-step3-4': 'Elsa &#187;',
                'p1-step4-1': 'Warning',
                'p1-step4-2': 'Try To Control Yourself',
                'p1-step4-3': 'Play Game',
                'p2-step1-1': 'Adult Games',
                'p2-step1-2': 'You You won\'t last even 40 seconds!',
				'p2-step1-3': 'Start Game',
                'p2-step1-4': 'By clicking on START GAME you confirm you\'re over 18',
                'p2-step2-1': 'Before we can allow you to play our adult games, we need to ask some quick questions.',
                'p2-step2-2': 'This will personalize your gaming experience to make more sensations.',
                'p2-step3-1': 'Our games are very addictive and you\'ll see a lot of sexual scenes. Can you handle it?',
                'p2-step3-2': 'Yes',
				'p2-step3-3': 'No',
				'p2-step2-3': 'Continue',
                'p2-step4-1': 'Who would you like to take to bed in these games?',
                'p2-step4-2': 'Your Mom Or Family',
                'p2-step4-3': 'Neighbor',
                'p2-step4-4': 'Famous Cartoons',
                'p2-step4-5': 'Others',
                'p2-step5-1': 'How big would you like her tits to be?',
                'p2-step5-2': 'Small',
                'p2-step5-3': 'Medium',
                'p2-step5-4': 'Big',
                'p2-step5-5': 'Huge',
                'p2-step6-1': 'How do you like her pussy?',
                'p2-step6-2': 'Shaved',
                'p2-step6-3': 'Trimmed',
                'p2-step6-4': 'Hairy',
                'p2-step7-1': 'Nice! We have over 1800 games for you. You can play single player & multiplayer',
                'p2-step7-2': 'But first, which type of game would you like to play?',
                'p2-step7-3': 'Quick Cum Game',
                'p2-step7-4': 'Role Playing Game',
                'p2-step8-1': 'Would you like the game to be hardcore?',
                'p2-step8-2': 'Yes',
                'p2-step8-3': 'No',
                'p2-step9-1': 'Is your door locked and are you ready to proceed now?',
                'p2-step9-2': 'Yes',
                'p2-step9-3': 'No',
                'p2-step10-1': 'How fast do you want to finish it?',
                'p2-step10-2': 'In 20 Seconds',
                'p2-step10-3': 'In 5 Minutes',
                'p2-step11-1': 'How many times do you want to finish it?',
                'p2-step11-2': 'Two Times',
                'p2-step11-3': 'Just Once',
                'p2-step12-1': 'Choose Game Difficulty',
                'p2-step12-2': 'Easy',
                'p2-step12-3': 'Normal',
                'p2-step12-4': 'Hard',
                'p2-step12-5': 'Extreme',
                'p2-step13-1': 'You will need to create an account and verify your age in order to access this game.  Do you agree these terms?',
                'p2-step13-2': 'Yes',
                'p2-step13-3': 'No',
                'p2-step14-1': 'Analyzing...',
                'p2-step15-1': 'Congrats!',
                'p2-step15-2': 'We found 11,131 players with your preferences currently online.',
                'p2-step15-3': 'Continue',
                'p2-step16-1': 'Please remember:',
                'p2-step16-2': '1. Our games are extremely addicting',
                'p2-step16-3': '2. We recommend playing alone',
                'p2-step16-4': '3. Lock your door before playing',
                'p2-step16-5': 'I Agree',
                'p2-step17-1': 'This game is compatible with',
                'p2-step17-2': 'No download is required.',
                'p2-step17-3': 'Continue',
                'p2-step18-1': 'Finding game room.',
                'p2-step18-2': 'Game found!',
                'p2-step18-3': 'Checking the answers!',
                'p2-step18-4': 'Browser compatibility detection!',
                'p2-step18-5': 'is compatible with the game!',
                'p2-step18-6': 'Continue',
                'faq1':'Got Questions?',
                'faq2':'Consult our FAQ',
                'faq':'FAQ',
                'faq-1':'What\'s GameBater?',
                'faq-2':'GameBater is the largest adult gaming community on the web! Thousands of sex games are played every day, online and offline.',
                'faq-3':'Do I have to pay for it?',
                'faq-4':'Playing our games is absolutely FREE! All you need is a valid email, and you’re good to go!',
                'faq-5':'If it\'s free, why do you need my credit card?',
                'faq-6':'Credit card authentication is our method of age verification. GameBater is only accessible to those that have reached the legal age of 18 and over.',
                'faq-7':'Do I need an Internet connection to play?',
                'faq-8':'No. Once you have signed up you can play online or offline.',
                'faq-9':'Can I play these games on multiple devices?',
                'faq-10':'Yes. You can play games on any number of devices.',
                'faq-11':'Is it safe and secure?',
                'faq-12':'We value your privacy and security and will never share your information. Your activity on GameBater is 100% private and discreet.',
                'faq-13':'Do I need to install an app or any software?',
                'faq-14':'Absolutely not! GameBater is 100% web-based and requires no installation of any software or add-ons. Just sign-up for FREE, and you’re good to go!',
                'faq-15':'Why am I forwarded to a different page after I answer the questions?',
                'faq-16':'GameBater works with various partners to provide you with the best possible gaming experience, but you can be certain that your information is transmitted safely and securely.'
			},
            'fr': {
				'title': 'GameBater - Essayez de ne pas jouir',
				'p1-step1-1': 'Verrouillez votre porte avant de commncer à jouer à ce jeu!',
                'p1-step1-2': 'Ne répandez pas la nouvelle!',
				'p1-step1-3': 'Jouer au jeu',
                'p1-step2-1': 'Travaille-la, Profitez-la',
                'p1-step2-2': 'Féconder',
                'p1-step2-3': 'Non, merci',
                'p1-step2-4': 'Continuez',
                'p1-step3-1': 'Choisissez votre premier',
                'p1-step3-2': 'Рartenaire sexuel',
                'p1-step3-3': '&#171; Lisa',
                'p1-step3-4': 'Elsa &#187;',
                'p1-step4-1': 'Attention',
                'p1-step4-2': 'Essayez de Rester calme!',
                'p1-step4-3': 'Jouer au jeu',
                'p2-step1-1': 'Des jeux pour adultes',
                'p2-step1-2': 'Vous ne tiendras même pas 40 secondes',
				'p2-step1-3': 'Commencez à jouer',
                'p2-step1-4': 'En cliquant sur COMMENCEZ A JOUER vous confirmez avoir plus de 18 ans',
                'p2-step2-1': 'Avant de vous donner accès aux jeux pour adultes, nous devons vous poser quelques questions.',
                'p2-step2-2': 'Cela personnaliser votre expérience de jeu pour vous éprouver plus de sensations.',
				'p2-step2-3': 'Continuez',
                'p2-step3-1': 'Nos jeux sont très addictifs et vous verrez beaucoup de scènes de sexe. Pourrez vous supporter cela?',
                'p2-step3-2': 'Oui',
				'p2-step3-3': 'Non',
                'p2-step4-1': 'Qui aimeriez-vous emmener au lit dans ces jeux?',
                'p2-step4-2': 'Votre mère ou votre famille',
                'p2-step4-3': 'Un voisin',
                'p2-step4-4': 'Des personnages des dessins animés',
                'p2-step4-5': 'Autres',
                'p2-step5-1': 'Quelle taille de seins préférerez vous?',
                'p2-step5-2': 'Petits',
                'p2-step5-3': 'Moyens',
                'p2-step5-4': 'Gros',
                'p2-step5-5': 'Enormes',
                'p2-step6-1': 'Comment aimeriez-vous sa chatte?',
                'p2-step6-2': 'Rasée',
                'p2-step6-3': 'Poils coupés',
                'p2-step6-4': 'Poilue',
                'p2-step7-1': 'Parfait! Nous avons plus de 1800 jeux pour vous. Vous pouvez jouer en solo ou en mode multijoueur',
                'p2-step7-2': 'Mais d\'abord, à quel type de jeu aimeriez-vous jouer?',
                'p2-step7-3': 'Jeu pour jouir rapidement',
                'p2-step7-4': 'Jeu de rôles',
                'p2-step8-1': 'Aimeriez-vous que le jeu soit hard?',
                'p2-step8-2': 'Oui',
                'p2-step8-3': 'Non',
                'p2-step9-1': 'Vous avez verrouillé votre porte et vous êtes prêt à procéder?',
                'p2-step9-2': 'Oui',
                'p2-step9-3': 'Non',
                'p2-step10-1': 'À quelle vitesse voulez-vous terminer?',
                'p2-step10-2': 'En 20 secondes',
                'p2-step10-3': 'En 5 minutes',
                'p2-step11-1': 'Combien de fois voulez-vous terminer?',
                'p2-step11-2': '2 fois',
                'p2-step11-3': 'Une seule fois',
                'p2-step12-1': 'Choisissez la difficulté du jeu',
                'p2-step12-2': 'Facile',
                'p2-step12-3': 'Normal',
                'p2-step12-4': 'Difficile',
                'p2-step12-5': 'Extrême',
                'p2-step13-1': 'Pour commencer à créer votre personnage, vous devez choisir votre nom d\'utilisateur et votre mot de passe. Comprenez-vous et acceptez-vous nos conditions?',
                'p2-step13-2': 'Oui',
                'p2-step13-3': 'Non',
                'p2-step14-1': 'Analyse en cours',
                'p2-step15-1': 'Félicitations',
                'p2-step15-2': 'Nous avons trouvé 11,131 joueurs avec vos préférences qui sont actuellement en ligne',
                'p2-step15-3': 'Continuez',
                'p2-step16-1': 'N\'oubliez pas:',
                'p2-step16-2': '1. Nos jeux sont extrêmement addictifs',
                'p2-step16-3': '2. Nous recommandons de jouer seul',
                'p2-step16-4': '3. Verrouillez votre porte avant de jouer',
                'p2-step16-5': 'Je suis d\'accord',
                'p2-step17-1': 'Notre simulateur est compatible avec',
                'p2-step17-2': 'Aucun téléchargement n\'est requis',
                'p2-step17-3': 'Continuez',
                'p2-step18-1': 'Finding game room.',
                'p2-step18-2': 'Jeu trouvé!',
                'p2-step18-3': 'Vérification des réponses',
                'p2-step18-4': 'Détection de la compatibilité du navigateur',
                'p2-step18-5': 'est compatible avec le jeu!',
                'p2-step18-6': 'Continuez',
                'faq1':'Got Questions?',
                'faq2':'Consult our FAQ',
                'faq':'FAQ',
                'faq-1':'Qu\'est-ce que GameBater?',
                'faq-2':'GameBater est la plus grande communauté de jeux pour adultes sur le Web! Des milliers de jeux sexuels sont joués chaque jour, en ligne et hors ligne.',
                'faq-3':'Dois-je payer pour jouer?',
                'faq-4':'Jouer à nos jeux est complètement GRATUIT! Tout ce dont vous avez besoin, c\'est une adresse e-mail valide, et vous êtes prêt pour y aller!',
                'faq-5':'Si c\'est gratuit, pourquoi avez-vous besoin de ma carte de crédit?',
                'faq-6':'L\'authentification par carte de crédit est notre moyen de vérifier l\'âge. GameBater n\'est accessible qu\'aux personnes de plus de 18 ans.',
                'faq-7':'Dois-je avoit une connexion internet pour jouer?',
                'faq-8':'Non. Une fois inscrit, vous pouvez jouer en ligne ou hors ligne.',
                'faq-9':'Puis-je jouer sur plusieurs appareils?',
                'faq-10':'Oui. Vous pouvez jouer sur plusieurs appareils.',
                'faq-11':'Est-ce sûr et sécurisé?',
                'faq-12':'Nous faisons attention à la confidentialité et la sécurité de vos données et ne partagerons jamais vos informations. Votre activité sur GameBater est 100% privée et sécurisée.',
                'faq-13':'Dois-je installer une application ou un logiciel?',
                'faq-14':'Pas du tout ! GameBater est 100% gratuit et ne nécessite aucune installation de logiciel ou d\'add-ons. Inscrivez-vous GRATUITEMENT et vous êtes prêt à jouer!',
                'faq-15':'Pourquoi suis-je redirigé vers une autre page après avoir répondu aux questions?',
                'faq-16':'GameBater travaille avec différents partenaires afin de vous offrir la meilleure expérience de jeu possible, mais vous pouvez être sûr que vos informations seront traîtées en toute sécurité.'
			},
            'de': {
				'title': 'GameBater - Versuche nicht zu kommen',
				'p1-step1-1': 'Schließ deine Tür ab, bevor du dieses Spiel spielst!',
                'p1-step1-2': 'Erzählen Sie es nicht weiter!',
				'p1-step1-3': 'Spielen',
                'p1-step2-1': 'Erschaff sie dir, Viel Spaß!',
                'p1-step2-2': 'Schwängere sie!',
                'p1-step2-3': 'Nein, danke',
                'p1-step2-4': 'Weiter',
                'p1-step3-1': 'Wähle deinen ersten',
                'p1-step3-2': 'Sexpartner',
                'p1-step3-3': '&#171; Lisa',
                'p1-step3-4': 'Elsa &#187;',
                'p1-step4-1': 'Warnung',
                'p1-step4-2': 'Versuche haltet euch in der Hand!',
                'p1-step4-3': 'Spielen',
                'p2-step1-1': 'Adult Spiele',
                'p2-step1-2': 'Du wirst nicht einmal 40 Sekunden durchhalten!',
				'p2-step1-3': 'Spiel starten',
                'p2-step1-4': 'Indem du auf SPIEL STARTEN klickst, bestätigst du, dass du mindestens 18 Jahre alt bist.',
                'p2-step2-1': 'Bevor wir dir erlauben können, dieses Spiel zu spielen, müssen wir dir ein paar Fragen stellen.',
                'p2-step2-2': 'So wird deine Spielerfahrung noch persönlicher und du damit Sie noch mehr Nervenkitzel haben.',
				'p2-step2-3': 'Weiter',
                'p2-step3-1': 'Unsere Spiele machen einfach süchtig und du wirst sehr viele Szenen mit sexuellen Handlungen sehen. Kannst du damit umgehen?',
                'p2-step3-2': 'Ja',
				'p2-step3-3': 'Nein',
                'p2-step4-1': 'Wen würdest du gerne in diesen Spielen mit ins Bett nehmen?',
                'p2-step4-2': 'Deine Mutter oder Familie',
                'p2-step4-3': 'Nachbarn',
                'p2-step4-4': 'Bekannte Comicfiguren',
                'p2-step4-5': 'Andere',
                'p2-step5-1': 'Wie groß sollen ihre Brüste sein?',
                'p2-step5-2': 'Klein',
                'p2-step5-3': 'Mittel',
                'p2-step5-4': 'Groß',
                'p2-step5-5': 'Riesig',
                'p2-step6-1': 'Wie soll ihre Muschi aussehen?',
                'p2-step6-2': 'Rasiert',
                'p2-step6-3': 'Getrimmt',
                'p2-step6-4': 'Behaart',
                'p2-step7-1': 'Sehr schön! Wir bieten dir mehr als 1800 Spiele. Du kannst einzeln oder im Multiplayer-Modus spielen.',
                'p2-step7-2': 'Aber zunächst: Welche Art von Spiel möchtest du spielen?',
                'p2-step7-3': 'Ein schnelles Abspritz-Spiel',
                'p2-step7-4': 'Ein Rollenspiel',
                'p2-step8-1': 'Wie hart soll es im Spiel zur Sache gehen?',
                'p2-step8-2': 'Ja',
                'p2-step8-3': 'Nein',
                'p2-step9-1': 'Ist deine Tür zu und bist du bereit, Vorgehen?',
                'p2-step9-2': 'Ja',
                'p2-step9-3': 'Nein',
                'p2-step10-1': 'Wie schnell willst du beenden?',
                'p2-step10-2': 'In 20 Sekunden',
                'p2-step10-3': 'In 5 Minuten',
                'p2-step11-1': 'Wie oft willst du beenden?',
                'p2-step11-2': 'Zweimal',
                'p2-step11-3': 'Nur einmal',
                'p2-step12-1': 'Wähle den Schwierigkeitsgrad',
                'p2-step12-2': 'Einfach',
                'p2-step12-3': 'Normal',
                'p2-step12-4': 'Schwierig',
                'p2-step12-5': 'Extrem schwierig',
                'p2-step13-1': 'Um dein Profil zu erstellen, musst du für diese Spiele einen Benutzernamen und ein Passwort auswählen. Hast du unsere AGB verstanden und akzeptiert?',
                'p2-step13-2': 'Ja',
                'p2-step13-3': 'Nein',
                'p2-step14-1': 'Überprüfen',
                'p2-step15-1': 'Gratulation',
                'p2-step15-2': 'Aktuell sind 11.331 Spieler mit deinen Vorzügen online',
                'p2-step15-3': 'Weiter',
                'p2-step16-1': 'Denk daran:',
                'p2-step16-2': '1. Unsere Spiele sind extrem anziehend.',
                'p2-step16-3': '2. Wir empfehlen, dass du sie alleine spielst.',
                'p2-step16-4': '3. Schließe deine Tür, bevor du mit dem Spiel beginnst.',
                'p2-step16-5': 'Verstanden',
                'p2-step17-1': 'Unser Simulator ist kompatibel mit',
                'p2-step17-2': 'Kein Download erforderlich.',
                'p2-step17-3': 'Weiter',
                'p2-step18-1': 'Finding game room',
                'p2-step18-2': 'Spiel gefunden!',
                'p2-step18-3': 'Antworten werden überprüft',
                'p2-step18-4': 'Überprüfung der Kompatibilität mit dem Browser',
                'p2-step18-5': 'ist mit dem Spiel kompatibel!',
                'p2-step18-6': 'Weiter',
                'faq1':'Got Questions?',
                'faq2':'Consult our FAQ',
                'faq':'FAQ',
                'faq-1':'Was ist GameBater?',
                'faq-2':'GameBater ist die größte Adult Gaming Community im Internet! Hier werden täglich Tausende Sexspiele gespielt, on- und offline.',
                'faq-3':'Muss ich dafür bezahlen?',
                'faq-4':'Unsere Spiele sind vollkommen KOSTENLOS! Du brauchst nur eine gültige E-Mail-Adresse und schon kannst du loslegen!',
                'faq-5':'Warum brauche ich eine Kreditkarte, obwohl die Spiele kostenlos sind?',
                'faq-6':'Die Authentifizierung mittels Kreditkarte ist unsere Methode zur Altersüberprüfung. GameBater ist nur für Personen zugängig, die 18 Jahre alt oder älter sind.',
                'faq-7':'Brauche ich eine Internetverbindung, um zu spielen?',
                'faq-8':'Nein. Sobald du dich angemeldet hast, kannst du online oder offline spielen.',
                'faq-9':'Kann ich diese Spiele auf mehreren Geräten spielen?',
                'faq-10':'Ja. Du kannst auf einer unbeschränkten Anzahl von Geräten spielen.',
                'faq-11':'Ist das alles sicher?',
                'faq-12':'Wir legen Wert auf deine Privatsphäre und deine Sicherheit. Wir geben keine Daten weiter. Deine Aktivitäten bei GameBater bleiben zu 100 % diskret.',
                'faq-13':'Muss ich eine App oder eine Software installieren?',
                'faq-14':'Auf keinen Fall! GameBater ist zu 100 % webbasiert. Es ist keine Installation einer Software oder von eventuellen Add-Ons nötig. Einfach KOSTENLOS anmelden und schon kann es losgehen!',
                'faq-15':'Warum werde ich nach der Beantwortung der Fragen auf eine andere Seite weitergeleitet?',
                'faq-16':'GameBater arbeitet mit verschiedenen Partnern zusammen, um dir die bestmögliche Spielerfahrung zu bieten. Du kannst aber sicher sein, dass deine Daten sicher und diskret übermittelt werden.'
			},
            'it': {
				'title': 'GameBater - Prova a non venire',
				'p1-step1-1': 'Chiuditi a chiave prima di iniziare questo gioco!',
                'p1-step1-2': 'Non diffondere la notizia!',
				'p1-step1-3': 'Inizia il gioco',
                'p1-step2-1': 'Creala e goditi',
                'p1-step2-2': 'Ingravidala',
                'p1-step2-3': 'No, grazie',
                'p1-step2-4': 'Continua',
                'p1-step3-1': 'Scegli la tua prima',
                'p1-step3-2': 'Partner sessuale',
                'p1-step3-3': '&#171; Lisa',
                'p1-step3-4': 'Elsa &#187;',
                'p1-step4-1': 'Attenzione',
                'p1-step4-2': 'Cerca di mantenerti!',
                'p1-step4-3': 'Inizia il gioco',
                'p2-step1-1': 'Giochi per adulti',
                'p2-step1-2': 'Non durerai nemmeno 40 secondi',
				'p2-step1-3': 'Inizia il gioco',
                'p2-step1-4': 'Cliccando su INIZIA IL GIOCO confermi di avere più di 18 anni',
                'p2-step2-1': 'Prima che tu possa divertirti con i nostri giochi, dobbiamo farti qualche domanda.',
                'p2-step2-2': 'Questo ci permetterà di personalizzare la tua esperienza di gioco per provare ancora più emozioni.',
				'p2-step2-3': 'Continua',
                'p2-step3-1': 'I nostri giochi sono molto coinvolgenti e vedrai un sacco di scene di sesso. Riuscirai a controllarti?',
                'p2-step3-2': 'Si',
				'p2-step3-3': 'No',
                'p2-step4-1': 'Chi vorresti portare a letto in questi giochi?',
                'p2-step4-2': 'Tua madre o la tua famiglia',
                'p2-step4-3': 'I vicini',
                'p2-step4-4': 'Cartoni animati famosi',
                'p2-step4-5': 'Altri',
                'p2-step5-1': 'Quanto vorresti che fossero grosse le sue tette?',
                'p2-step5-2': 'Piccole',
                'p2-step5-3': 'Medie',
                'p2-step5-4': 'Grandi',
                'p2-step5-5': 'Enormi',
                'p2-step6-1': 'Come ti piace la sua fica?',
                'p2-step6-2': 'Depilata',
                'p2-step6-3': 'Rifinita',
                'p2-step6-4': 'Pelosa',
                'p2-step7-1': 'Fantastico! Abbiamo oltre 1800 giochi per te. Puoi giocare da solo e in modalità multiplayer.',
                'p2-step7-2': 'Prima però, a che tipo di gioco vorresti giocare?',
                'p2-step7-3': 'Gioco sborra veloce',
                'p2-step7-4': 'Gioco di ruolo',
                'p2-step8-1': 'Vuoi che il gioco sia hardcore?',
                'p2-step8-2': 'Si',
                'p2-step8-3': 'No',
                'p2-step9-1': 'Hai chiuso la porta e sei pronto a continuare?',
                'p2-step9-2': 'Si',
                'p2-step9-3': 'No',
                'p2-step10-1': 'Quanto velocemente vuoi finire?',
                'p2-step10-2': 'In 20 secondi',
                'p2-step10-3': 'In 5 minuti',
                'p2-step11-1': 'Quante volte vuoi finire?',
                'p2-step11-2': 'Due volte',
                'p2-step11-3': 'Una volta sola',
                'p2-step12-1': 'Scegli il livello di difficoltà del gioco',
                'p2-step12-2': 'Facile',
                'p2-step12-3': 'Normale',
                'p2-step12-4': 'Difficile',
                'p2-step12-5': 'Estremo',
                'p2-step13-1': 'Per iniziare a creare il tuo personaggio, devi selezionare il tuo nome utente e la tua password per il gioco. Hai capito e accetti le nostre condizioni?',
                'p2-step13-2': 'Si',
                'p2-step13-3': 'No',
                'p2-step14-1': 'Analizzando',
                'p2-step15-1': 'Congratulazioni',
                'p2-step15-2': 'In questo momento ci sono 11.131 giocatori online con le tue preferenze',
                'p2-step15-3': 'Continua',
                'p2-step16-1': 'Ricordati:',
                'p2-step16-2': '1. I nostri giochi sono davvero coinvolgenti.',
                'p2-step16-3': '2. Ti consigliamo di giocare da solo.',
                'p2-step16-4': '3. Chiudi la porta prima di iniziare a giocare.',
                'p2-step16-5': 'Acconsento',
                'p2-step17-1': 'Il nostro simulatore è compatibile con',
                'p2-step17-2': 'Non è richiesto alcun download',
                'p2-step17-3': 'Continua',
                'p2-step18-1': 'Finding game room.',
                'p2-step18-2': 'Gioco trovato!',
                'p2-step18-3': 'Verifica delle risposte',
                'p2-step18-4': 'Rilevamento della compatibilità del browser',
                'p2-step18-5': 'è compatibile con questo gioco!',
                'p2-step18-6': 'Continua',
                'faq1':'Got Questions?',
                'faq2':'Consult our FAQ',
                'faq':'FAQ',
                'faq-1':'Cos\'è GameBater?',
                'faq-2':'GameBater è la più grande comunità di gioco per adulti sul web! Ogni giorno potrai divertirti con migliaia di giochi online e offline.',
                'faq-3':'É a pagamento?',
                'faq-4':'I nostri giochi sono GRATIS! Tutto ciò di cui hai bisogno è un\'email valida, e sei pronto a iniziare!',
                'faq-5':'Se sono gratuiti, perché avete bisogno della mia carta di credito?',
                'faq-6':'La conferma tramite carta di credito è il nostro metodo per verificare l\'età. GameBater è accessibile solo per chi è maggiorenne.',
                'faq-7':'Ho bisogno di una connessione internet per giocare?',
                'faq-8':'No. Una volta iscritto potrai giocare online o offline.',
                'faq-9':'Posso giocare con diversi dispositivi?',
                'faq-10':'Sì, è possibile giocare da diversi dispositivi.',
                'faq-11':'Il sito é sicuro e protetto?',
                'faq-12':'Per noi la tua privacy e la tua sicurezza sono importanti e non condivideremo mai le tue informazioni. La tua attività su GameBater resterà riservata al 100%.',
                'faq-13':'Devo installare un\'applicazione o un software?',
                'faq-14':'Assolutamente no! GameBater è interamente basato sul web e non richiede l\'installazione di alcun software o di programmi aggiuntivi. Basta registrarsi GRATUITAMENTE, e sei pronto a iniziare!',
                'faq-15':'Perché vengo reindirizzato ad un\'altra pagina dopo aver risposto alle domande?',
                'faq-16':'GameBater collabora con vari partner per offrirti la migliore esperienza di gioco possibile, ma puoi essere certo che le tue informazioni saranno trasmesse in modo sicuro e protetto.'
			}, 
            'ru': {
				'title': 'GameBater - Постарайся не кончить',
				'p1-step1-1': 'Прежде чем играть, закрой за собой дверь!',
                'p1-step1-2': 'Никому не рассказывайте!',
				'p1-step1-3': 'Играть',
                'p1-step2-1': 'Создай девушку мечты',
                'p1-step2-2': 'и наслаждайся',
                'p1-step2-3': 'Нет, спасибо',
                'p1-step2-4': 'Продолжить',
                'p1-step3-1': 'Выбери своего первого',
                'p1-step3-2': 'полового партнера',
                'p1-step3-3': '&#171; Елена',
                'p1-step3-4': 'Эльза &#187;',
                'p1-step4-1': 'Внимание',
                'p1-step4-2': 'Постарайся держать себя в руках!',
                'p1-step4-3': 'Играть', 
                'p2-step1-1': 'Игры для взрослых',
                'p2-step1-2': 'Вы сможете продержаться больше 40 секунд?',
				'p2-step1-3': 'Начать игру',
                'p2-step1-4': 'Нажимая на кнопку "ИГРАТЬ", вы подтверждаете, что вам исполнилось 18 лет',
                'p2-step2-1': 'Перед тем как дать вам возможность сыграть, нам нужно задать несколько вопросов.',
				'p2-step2-2': 'Это позволит настроить ваш индивидуальный игровой процесс, чтобы вы испытали больше ощущений.',  
				'p2-step2-3': 'Продолжить',
                'p2-step3-1': 'Наши игры крайне увлекательны, и вам предстоит увидеть множество сексуальных сцен. Вы справитесь?',
                'p2-step3-2': 'Да',
				'p2-step3-3': 'Нет',
                'p2-step4-1': 'Кого бы вы хотели затащить в постель в этих играх?',
                'p2-step4-2': 'Вашу маму или члена семьи',
                'p2-step4-3': 'Соседку',
                'p2-step4-4': 'Мультипликационного персонажа',
                'p2-step4-5': 'Прочее',
                'p2-step5-1': 'Каким должен быть размер ее груди?',
                'p2-step5-2': 'Маленьким',
                'p2-step5-3': 'Средним',
                'p2-step5-4': 'Большим',
                'p2-step5-5': 'Огромным',
                'p2-step6-1': 'Какой должна быть ее киска?',
                'p2-step6-2': 'Бритой',
                'p2-step6-3': 'Стриженой',
                'p2-step6-4': 'Волосатой',
                'p2-step7-1': 'Прекрасно! У нас для вас более 1800 игр. Вы можете играть в режиме одиночной или многопользовательской игры',
                'p2-step7-2': 'Но сначала, в какую игру вы хотели бы сыграть?',
                'p2-step7-3': 'Игра с быстрым окончанием',
                'p2-step7-4': 'Ролевая игра',
                'p2-step8-1': 'Хотите добавить в игру хардкор?',
                'p2-step8-2': 'Да',
                'p2-step8-3': 'Нет',
                'p2-step9-1': 'Вы заперли дверь и готовы продолжить?',
                'p2-step9-2': 'Да',
                'p2-step9-3': 'Нет',
                'p2-step10-1': 'Как быстро вы хотели бы закончить?',
                'p2-step10-2': 'За 20 секунд',
                'p2-step10-3': 'За 5 минут',
                'p2-step11-1': 'Сколько раз вы хотели бы закончить?',
                'p2-step11-2': 'Два раза',
                'p2-step11-3': 'Один раз',
                'p2-step12-1': 'Выберите сложность игры',
                'p2-step12-2': 'Простая',
                'p2-step12-3': 'Стандартная',
                'p2-step12-4': 'Сложная',
                'p2-step12-5': 'Очень сложная',
                'p2-step13-1': 'Чтобы создать вашего персонажа, выберите игровой никнейм и пароль. Вы соглашаетесь и принимаете наши условия?',
                'p2-step13-2': 'Да',
                'p2-step13-3': 'Нет',
                'p2-step14-1': 'Анализируем',
                'p2-step15-1': 'Поздравляем',
                'p2-step15-2': 'Мы нашли 11 131 игроков онлайн, соответствующих вашим предпочтениям',
                'p2-step15-3': 'Продолжить',
                'p2-step16-1': 'Пожалуйста, помните:',
                'p2-step16-2': '1. Наши игры крайне увлекательны',
                'p2-step16-3': '2. Мы рекомендуем вам уединиться',
                'p2-step16-4': '3. Прежде чем начать игру, закройте дверь',
                'p2-step16-5': 'Я согласен',
                'p2-step17-1': 'Наш симулятор поддерживается ',
                'p2-step17-2': 'Скачивание не требуется',
                'p2-step17-3': 'Продолжить',
                'p2-step18-1': 'Поиск игрового сервера',
                'p2-step18-2': 'Игра найдена!',
                'p2-step18-3': 'Проверка ответов',
                'p2-step18-4': 'Проверка совместимости браузера',
                'p2-step18-5': 'поддерживает игру!',
                'p2-step18-6': 'Продолжить',
                'faq1':'Есть вопросы?',
                'faq2':'Обратитесь к ответам на часто задаваемые вопросы',
                'faq':'Часто задаваемые вопросы',
                'faq-1':'Что такое GameBater?',
                'faq-2':'GameBater - это крупнейшее в сети игровое сообщество для взрослых! Ежедневно пользователи играют в тысячи секс игр онлайн и офлайн.',
                'faq-3':'Мне нужно за это платить?',
                'faq-4':'Все наши игры абсолютно БЕСПЛАТНЫ! Вам нужен только действующий адрес электронной почты и можно начинать!',
                'faq-5':'Если игра бесплатна, зачем вам моя кредитная карта?',
                'faq-6':'Аутентификация с помощью карты используется нами для подтверждения вашего возраста. Платформа GameBater доступна только тем пользователям, которым исполнилось 18 лет.',
                'faq-7':'Для игры мне потребуется интернет соединение?',
                'faq-8':'Нет. После регистрации вы сможете играть онлайн или офлайн.',
                'faq-9':'Можно ли играть в эти игры с нескольких устройств?',
                'faq-10':'Да. Вы сможете играть в игры с любого количества устройств.',
                'faq-11':'Это надежно и безопасно?',
                'faq-12':' Мы ценим вашу конфиденциальность и безопасность и никогда не делимся вашей информацией. Ваши действия на платформе GameBater на 100% конфиденциальны и скрыты от посторонних.',
                'faq-13':'Нужно ли мне устанавливать приложение или программное обеспечение?',
                'faq-14':'Точно нет! GameBeater на 100% веб-интерфейс и не требует установки какого-либо программного обеспечения или дополнений. Просто зарегистрируйтесь БЕСПЛАТНО, и все готово!',
                'faq-15':'Почему меня перенаправили на стороннюю страницу после ответов на вопросы?',
                'faq-16':' GameBater работает с различными партнерами, чтобы предоставить вам наилучшие игровые возможности, но вы можете быть уверены, что ваша информация передается безопасно и надежно.'
				
				
			}
		}	
		if(typeof store[localize] == 'undefined') {
            localize = def;
        }
        
		return store[localize][str];
      
	}
	document.title = lang('title');
	window.lang = lang;
})(window);
